require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TypeEventsController do

  # This should return the minimal set of attributes required to create a valid
  # TypeEvent. As you add validations to TypeEvent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TypeEventsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all type_events as @type_events" do
      type_event = TypeEvent.create! valid_attributes
      get :index, {}, valid_session
      assigns(:type_events).should eq([type_event])
    end
  end

  describe "GET show" do
    it "assigns the requested type_event as @type_event" do
      type_event = TypeEvent.create! valid_attributes
      get :show, {:id => type_event.to_param}, valid_session
      assigns(:type_event).should eq(type_event)
    end
  end

  describe "GET new" do
    it "assigns a new type_event as @type_event" do
      get :new, {}, valid_session
      assigns(:type_event).should be_a_new(TypeEvent)
    end
  end

  describe "GET edit" do
    it "assigns the requested type_event as @type_event" do
      type_event = TypeEvent.create! valid_attributes
      get :edit, {:id => type_event.to_param}, valid_session
      assigns(:type_event).should eq(type_event)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TypeEvent" do
        expect {
          post :create, {:type_event => valid_attributes}, valid_session
        }.to change(TypeEvent, :count).by(1)
      end

      it "assigns a newly created type_event as @type_event" do
        post :create, {:type_event => valid_attributes}, valid_session
        assigns(:type_event).should be_a(TypeEvent)
        assigns(:type_event).should be_persisted
      end

      it "redirects to the created type_event" do
        post :create, {:type_event => valid_attributes}, valid_session
        response.should redirect_to(TypeEvent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved type_event as @type_event" do
        # Trigger the behavior that occurs when invalid params are submitted
        TypeEvent.any_instance.stub(:save).and_return(false)
        post :create, {:type_event => { "name" => "invalid value" }}, valid_session
        assigns(:type_event).should be_a_new(TypeEvent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TypeEvent.any_instance.stub(:save).and_return(false)
        post :create, {:type_event => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested type_event" do
        type_event = TypeEvent.create! valid_attributes
        # Assuming there are no other type_events in the database, this
        # specifies that the TypeEvent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TypeEvent.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => type_event.to_param, :type_event => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested type_event as @type_event" do
        type_event = TypeEvent.create! valid_attributes
        put :update, {:id => type_event.to_param, :type_event => valid_attributes}, valid_session
        assigns(:type_event).should eq(type_event)
      end

      it "redirects to the type_event" do
        type_event = TypeEvent.create! valid_attributes
        put :update, {:id => type_event.to_param, :type_event => valid_attributes}, valid_session
        response.should redirect_to(type_event)
      end
    end

    describe "with invalid params" do
      it "assigns the type_event as @type_event" do
        type_event = TypeEvent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TypeEvent.any_instance.stub(:save).and_return(false)
        put :update, {:id => type_event.to_param, :type_event => { "name" => "invalid value" }}, valid_session
        assigns(:type_event).should eq(type_event)
      end

      it "re-renders the 'edit' template" do
        type_event = TypeEvent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TypeEvent.any_instance.stub(:save).and_return(false)
        put :update, {:id => type_event.to_param, :type_event => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested type_event" do
      type_event = TypeEvent.create! valid_attributes
      expect {
        delete :destroy, {:id => type_event.to_param}, valid_session
      }.to change(TypeEvent, :count).by(-1)
    end

    it "redirects to the type_events list" do
      type_event = TypeEvent.create! valid_attributes
      delete :destroy, {:id => type_event.to_param}, valid_session
      response.should redirect_to(type_events_url)
    end
  end

end
